<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="gk" failures="1" tests="3" name="Test" time="7.149" errors="0" timestamp="2024-10-05T19:31:13 IST">
  <testcase classname="day46.OrangeHRMListner" name="testLogo" time="0.031"/>
  <testcase classname="day46.OrangeHRMListner" name="testAppUrl" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/auth/login]
at day46.OrangeHRMListner.testAppUrl(OrangeHRMListner.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="day46.OrangeHRMListner" name="testHomePageTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testHomePageTitle -->
</testsuite> <!-- Test -->
